#!/usr/bin/env bash

for i in "$@"; do
  case $i in
  "-v" | "--verbose")
    # output the pokemon info to stderr
    OPT_VERBOSE=1
    ;;
  "-f" | "--fetch")
    # include system info alongside the sprite
    OPT_FETCH=1
    ;;
  esac
done

CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config} # should almost always return `$HOME/.config`
POTD_DIR="${CONFIG_DIR}/potd"                # the config directory that this script will use to store everything
POTD_CACHE="${POTD_DIR}/cache"               # used to record which sprites have appeared before
POKEGET_CMD='pokeget'                        # requires pokeget-rs for the pretty small sprites
POKEGET_ARGS=('')                            # add any extra args for pokeget-rs here
MAX_DEX_ID=905                               # max pokedex id in pokeget-rs. decrease this number to limit to specific generations.

# ansi escape codes for colours + style
HEAD='\e[34m'
DATA='\033[38;2;200;166;247m'
DATA='\e[35m'
SHINY='\e[33m'
BOLD='\e[1m'
RESET='\e[0m'

# seed the bash random number with the current date, snapped to midnight, as a unix timestamp
pokemon_seed=$(date --date "00:00" +%s)
RANDOM=${pokemon_seed}
pokedex_id=$((RANDOM % MAX_DEX_ID))
POKEGET_ARGS=("$pokedex_id" "${POKEGET_ARGS[@]}")
sprite_path="${POTD_CACHE}/${pokedex_id}"

# roll for a shiny
shiny_seed=$(date +%s)
shiny_seed=$((shiny_seed - (shiny_seed % 300)))

RANDOM=${shiny_seed}
shiny_roll=$((RANDOM % 128))
if [ $shiny_roll -eq 0 ]; then
  POKEGET_ARGS+=('--shiny')
  sprite_path="${sprite_path}-shiny"
fi

# check if this sprite has been saved yet
[ -d ${POTD_DIR} ] || mkdir ${POTD_DIR}
[ -d ${POTD_CACHE} ] || mkdir ${POTD_CACHE}
if ! [ -f ${sprite_path} ]; then
  echo "$pokemon_seed" >$sprite_path # first seen value
  $POKEGET_CMD ${POKEGET_ARGS[@]} >>$sprite_path 2>&1
fi

pokemon_name="$(sed '2q;d' $sprite_path)"
first_seen="$(head -n 1 $sprite_path)"

# extract the shiny encounter date if available
if [ $shiny_roll -eq 0 ]; then
  shiny_seen=$(head -n 1 "${sprite_path}")
else
  [ -f "${sprite_path}-shiny" ] && shiny_seen=$(head -n 1 "${sprite_path}-shiny") || shiny_seen=0
fi

# get system info (shamelessly lifted from cutefetch)
get_uptime() {
  local up=$(uptime)
  up=${up#*up }    # remove everything before "up "
  up=${up%%,*}     # remove everything after first comma
  echo $up | xargs # trim whitespace
}

systeminfo=()

if ! [ -z ${OPT_FETCH+x} ]; then
  systeminfo[0]="${BOLD}${HEAD}kn${RESET} ${DATA}$(uname -r | cut -f1 -d '-')"
  systeminfo[1]="${BOLD}${HEAD}sh${RESET} ${DATA}$(basename $SHELL)"
  systeminfo[2]="${BOLD}${HEAD}up${RESET} ${DATA}$(get_uptime)"

  # store the pokemon info along with the system info
  [ $shiny_roll -eq 0 ] && systeminfo[4]="${BOLD}${HEAD}potd${RESET} ${BOLD}${SHINY}${pokemon_name,,} (${pokedex_id})" || systeminfo[4]="${BOLD}${HEAD}potd${RESET} ${DATA}${pokemon_name,,} (${pokedex_id})"
  [ $first_seen -eq $pokemon_seed ] && systeminfo[5]="${BOLD}${HEAD}seen${RESET} ${DATA}today" || systeminfo[5]="${BOLD}${HEAD}seen${RESET} ${DATA}$((first_seen % 60 % 60 % 24)) days ago"

  case $shiny_seen in
  0)
    systeminfo[6]="${BOLD}${HEAD}shny${RESET} ${DATA}never seen"
    ;;
  $pokemon_seed)
    systeminfo[6]="${BOLD}${HEAD}shny${RESET} ${DATA}today"
    ;;
  *)
    systeminfo[6]="${BOLD}${HEAD}shny${RESET} ${DATA}$((shiny_seen % 60 % 60 % 24)) days ago"
    ;;
  esac
fi

# print the pokemon info to stderr if -v or --verbose was passed
[ -z ${OPT_VERBOSE+x} ] || >&2 echo -e "dex_id: ${pokedex_id}\npkmn_name: ${pokemon_name}\nshiny_roll: ${shiny_roll}\npkmn_seed: ${pokemon_seed}\nshiny_seed: ${shiny_seed}\nfirst_seen: ${first_seen}"

# iterate over every line in the sprite, appending system info when available
index=0
tail -n +3 ${sprite_path} | while IFS= read -r line; do
  [ $index -le ${#systeminfo[@]} ] && echo -e "${line}    ${systeminfo[$index]}" || echo "${line}"
  index=$((index + 1))
done
